---
authors:
    - Ansible Network Community (ansible-network)
dependencies:
    "ansible.netcommon": "*"
license_file: LICENSE
name: cli_rm_builder
namespace: ansible_network
readme: README.md
repository: https://github.com/ansible-network/cli_rm_builder
version: 0.0.1
