
- name: "Create the resource module directory structure"
  file:
    path: "{{ parent_directory }}/{{ item }}"
    state: directory
  with_items: "{{ resource_module_directories }}"

- name: Touch the __init__.py in each directory
  copy:
    content: ""
    dest: "{{ parent_directory }}/{{ item }}/__init__.py"
    force: no
  with_items: "{{ resource_module_directories }}"

- name: Copy argspec to a temporary file to format
  copy:
    # the prepended whitespace is needed to ensure that booleans are not lowercased
    content: " {{ (rm_documentation|ansible_network.cli_rm_builder.to_argspec)['argument_spec'] }}"
    dest: "{{ temp }}"
  changed_when: False

- name: Remove the whitespace from the argspec in temp file
  # the preceeding whitespace added in the previous task breaks `black`
  replace:
    path: "{{ temp }}"
    regexp: '^\s+'
    replace: ''
  changed_when: False

- name: Format dumped argspec using black with fixed line-length
  command: "black -l 79 {{ temp }}"
  changed_when: False

- name: Load formatted argspec and get other module kwargs
  set_fact:
    # this _has_ to be loaded as a string to preserve black formatting
    formatted_argspec: "{{ lookup('file', '{{ temp }}')|string() }}"

- name: Delete temp file
  file:
    path: "{{ temp }}"
    state: absent
  changed_when: False

- name: Template each of the files
  include: template.yml
  with_items: "{{ resource_module_templates }}"
  loop_control:
    loop_var: template
